acme_directory: "https://acme.zerossl.com/v2/DV90"
acme_version: 2
acme_revoke: false
acme_register_account: true
acme_external_account_binding_file: "acme_configuration/zero-ssl.private"
 
#Certificate Directory
acme_certificate_dir: acme_certificate
 
#Configure only one type of acme_method
#
#Example http-01 create certificate for acme_domain
#
#acme_method: http-01
#acme_domain: www.example.com
#acme_account_email: test@example.com

#Example dns-01 create a wildcard
#
#acme_method: dns-01
#acme_domain: example.com
#acme_account_email: test@example.com
#bind:
# server: 10.10.10.10
